# 1. Creating Arrays with array, arange, linspace, zeros, ones, full, eye


#### Numpy: 

NumPy is a Python library for fast numerical computations using arrays and matrices, along with a large collection of mathematical functions. In machine learning, it is used for data manipulation, linear algebra operations, and efficient handling of large datasets.



Explanation of Methods:

np.array(): Creates an array from a Python list or another array-like object.

np.arange(): Creates an array with values in a specified range and step size.

np.linspace(): Creates an array with a specified number of evenly spaced values between a start and end point.

np.zeros(): Creates an array of the specified shape filled with zeros.

np.ones(): Creates an array of the specified shape filled with ones.

np.full(): Creates an array filled with a specific value.

np.eye(): Creates an identity matrix with ones on the diagonal and zeros elsewhere.

In [27]:

# 1. Creating an array with array()
arr = np.array([1, 2, 3, 4, 5])
print("Array using np.array():\n", arr)

Array using np.array():
 [1 2 3 4 5]


In [11]:
# 2. Creating an array with arange() - creates an array with evenly spaced values within a given range
arr_arange = np.arange(0, 10,2)  # From 0 to 10 with step of 2
print("\nArray using np.arange():\n", arr_arange)


Array using np.arange():
 [0 2 4 6 8]


In [15]:
# 3. Creating an array with linspace() - creates an array with a specified number of evenly spaced values between a range
arr_linspace = np.linspace(0, 10, 5)  # 5 values between 0 and 10 (inclusive)
print("\nArray using np.linspace():\n", arr_linspace)


Array using np.linspace():
 [ 0.   2.5  5.   7.5 10. ]


In [19]:
# 4. Creating an array of zeros with zeros() - creates an array filled with zeros
arr_zeros = np.zeros((3, 4))  # 3x4 matrix of zeros
print("\nArray using np.zeros():\n", arr_zeros)


Array using np.zeros():
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [24]:
# 5. Creating an array of ones with ones() - creates an array filled with ones
arr_ones = np.ones((2, 3))  # 2x3 matrix of ones
print("\nArray using np.ones():\n", arr_ones)


Array using np.ones():
 [[1. 1. 1.]
 [1. 1. 1.]]


In [25]:
# 6. Creating an array with a specific value using full() - creates an array filled with a specific value
arr_full = np.full((2, 2), 7)  # 2x2 matrix filled with 7
print("\nArray using np.full():\n", arr_full)


Array using np.full():
 [[7 7]
 [7 7]]


In [26]:
# 7. Creating an identity matrix with eye() - creates an identity matrix
arr_eye = np.eye(4)  # 4x4 identity matrix
print("\nArray using np.eye():\n", arr_eye)


Array using np.eye():
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
