# Array Attributes, shape, dtype, ndim, size, itemsize, nbytes


shape – Returns a tuple indicating the dimensions of the array (e.g., rows and columns).

dtype – Shows the data type of the array elements (e.g., int32, float64).

ndim – Tells the number of dimensions (axes) in the array.

size – Gives the total number of elements in the array.

itemsize – Returns the size in bytes of one array element.

nbytes – Displays the total number of bytes consumed by the array.

In [12]:
import numpy as np


# Create a sample NumPy array
arr = np.array([[1,2,3],[10,20,30]])
print(arr)

[[ 1  2  3]
 [10 20 30]]


In [13]:
# Display array and attributes
print("Array:")
print(arr)
print("\nAttributes:")
print("Shape     :", arr.shape)      # (2, 3) – 2 rows, 3 columns
print("Dtype     :", arr.dtype)      # int32 – data type of each element
print("Ndim      :", arr.ndim)       # 2 – number of dimensions
print("Size      :", arr.size)       # 6 – total number of elements
print("Itemsize  :", arr.itemsize)   # 4 – size (in bytes) of each element
print("Nbytes    :", arr.nbytes)     # 24 – total memory used by array (6 * 4)

Array:
[[ 1  2  3]
 [10 20 30]]

Attributes:
Shape     : (2, 3)
Dtype     : int64
Ndim      : 2
Size      : 6
Itemsize  : 8
Nbytes    : 48
