### 1. Reshape, Flatten, Ravel, Transpose, Expand/Remove Dimensions

### 2. Arithmetic Operations (+, -, *, /, %, **)


# 1. Reshape, Flatten, Ravel, Transpose, Expand/Remove Dimensions

In [4]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])  # Shape: (2, 3)
print("Original:\n", arr, "\nShape:", arr.shape)

# 1. Reshape
reshaped = arr.reshape(3, 2)
print("\nReshaped to (3,2):\n", reshaped)



Original:
 [[1 2 3]
 [4 5 6]] 
Shape: (2, 3)

Reshaped to (3,2):
 [[1 2]
 [3 4]
 [5 6]]


In [5]:
# 2. Flatten (copy)
flat = arr.flatten()
print("\nFlatten (copy to 1D):\n", flat)


Flatten (copy to 1D):
 [1 2 3 4 5 6]


In [6]:
# 3. Ravel (view if possible)
ravel = arr.ravel()
print("\nRavel (1D view):\n", ravel)


Ravel (1D view):
 [1 2 3 4 5 6]


In [7]:
# 4. Transpose
trans = arr.T
print("\nTransposed:\n", trans)


Transposed:
 [[1 4]
 [2 5]
 [3 6]]


In [8]:
# 5. Expand dimensions (add new axis at position 0)
expanded = np.expand_dims(arr, axis=0)
print("\nExpanded dims at axis 0:\n", expanded, "\nShape:", expanded.shape)


Expanded dims at axis 0:
 [[[1 2 3]
  [4 5 6]]] 
Shape: (1, 2, 3)


In [9]:
# 6. Squeeze (remove axes with size=1)
squeezed = np.squeeze(expanded)
print("\nSqueezed:\n", squeezed, "\nShape:", squeezed.shape)


Squeezed:
 [[1 2 3]
 [4 5 6]] 
Shape: (2, 3)


# Operations

In [13]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([2, 5, 3])


print(a, " \n ", b)

[10 20 30]  
  [2 5 3]


In [14]:

# Addition
print("Addition:", a + b)       # [12 25 33]


Addition: [12 25 33]


In [15]:
# Subtraction
print("Subtraction:", a - b)    # [ 8 15 27]

Subtraction: [ 8 15 27]


In [16]:
# Multiplication
print("Multiplication:", a * b) # [20 100 90]

Multiplication: [ 20 100  90]


In [17]:

# Division
print("Division:", a / b)       # [5. 4. 10.]

Division: [ 5.  4. 10.]


In [18]:
# Modulus
print("Modulus:", a % b)        # [0 0 0]

Modulus: [0 0 0]


In [19]:
# Exponentiation
print("Exponentiation:", a ** b)  # [  100 3200000 27000]

Exponentiation: [    100 3200000   27000]
