### Logical Operations

### NaN Handling

### Unique Values, Sorting, and Counting

# 1. Logical operations

In [83]:
import numpy as np

# --- Logical Operations ---
arr1 = np.array([1, 10])
arr2 = np.array([4, 3])

arr1, arr2

(array([ 1, 10]), array([4, 3]))

In [84]:
# where: conditionally select values
np.where(arr1 > arr2, arr1, arr2)

array([ 4, 10])

In [85]:
np.where(arr1 < arr2, arr1, arr2)

array([1, 3])

In [86]:
items = np.array(["ref",'foam','watch','foam'])

np.where(items == 'foam')

(array([1, 3]),)

In [89]:
# any and all
arr1 = np.array([3,3,2,15,24])
np.any(arr1 > 19)

np.True_

In [91]:
ages = np.array([1,2,3,10])
np.all(ages < 6)

np.False_

In [94]:
# logical_and, logical_or
np.logical_and(20 > 2, 10 > 2)

np.True_

In [95]:
np.logical_or(3 > 2, 1 > 2)

np.True_

# Handling NAN Values

In [96]:
# --- NaN Handling ---
nan_arr = np.array([1.0, np.nan, 3, np.nan])
nan_arr

array([ 1., nan,  3., nan])

In [97]:
# isnan,
np.isnan(nan_arr)

array([False,  True, False,  True])

In [98]:
np.isfinite(nan_arr)

array([ True, False,  True, False])

In [100]:
# nan_to_num: replace nan and inf
np.nan_to_num(nan_arr, nan=100)

array([  1., 100.,   3., 100.])

# Unique Values, Sorting, and Counting

In [103]:
# unique
vals = np.array([1,2,3,3,3,1])
np.unique(vals)

array([1, 2, 3])

In [105]:
# bincount (useful for frequency of small integers)
# np.bincount(vals) counts the number of occurrences of each non-negative integer value in the array vals.
vals = np.array([1,2,3,3,3,4,4,4,4,4])
np.bincount(vals)

array([0, 1, 1, 3, 5])

In [106]:
# sort and argsort
ages = np.array([85, 100, 50, 5,10,15])
np.sort(ages)

array([  5,  10,  15,  50,  85, 100])

In [108]:
vals = np.array([1,2,20,3])
np.argsort(vals)

array([0, 1, 3, 2])