# Indexing in Numpy 


#### Indexing & Slicing (1D, 2D, 3D)

#### Boolean Indexing & Conditional Selection

#### Fancy Indexing with Lists & Arrays

### 1. Indexing & Slicing
##### 1D Array


arr1[2]: Accesses the 3rd element → 30

arr1[1:4]: Slices elements from index 1 to 3 → [20 30 40]

In [5]:
import numpy as np
arr1 = np.array([10, 20, 30, 40, 50])
print(arr1[2])       # Indexing
print(arr1[1:4])     # Slicing


30
[20 30 40]


##### 2D Array

arr2[1, 2]: Accesses row 1, column 2 → 6

arr2[0:2, 1:3]: Slices rows 0–1 and columns 1–2 → [[2 3], [5 6]]

In [10]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2[1, 2])        # Indexing
print(arr2[0:2, 1:3])    # Slicing


6
[[2 3]
 [5 6]]


#### 3D Array

arr3[1, 0, 1]: Accesses 2nd depth, 1st row, 2nd column → 6

arr3[:, 0:2, 0:2]: Slices entire depth with 2x2 sub-blocks

In [17]:
arr3 = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(arr3[1, 0, 1])         # Indexing
print(arr3[:, 0:1, 0:1])     # Slicing


6
[[[1]]

 [[5]]]


In [15]:
arr[1,0,1]


np.int64(40)

# 2. Boolean Indexing & Conditional Selection

In [18]:
arr = np.array(["Noor",'Jhon','Sara'])
print(arr[arr == "Noor"])


['Noor']


In [19]:
arr = np.array([10,20,30])
arr[arr>12]

array([20, 30])

In [20]:
arr = np.array([10,20,30])
arr[arr<12]

array([10])

# 3. Fancy Indexing with Lists & Arrays

In [21]:
arr = np.array([100, 200, 300, 400, 500])
print(arr[[0, 2, 4]])

[100 300 500]
