# -------------------------------
# Broadcasting Example
# -------------------------------

Broadcasting in NumPy is a technique that allows arithmetic operations between arrays of different shapes by automatically expanding their dimensions to make them compatible.

In [2]:
import numpy as np


a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])

broadcast_result = a + b  # Adds b to each row of a

broadcast_result

array([[11, 22, 33],
       [14, 25, 36]])

# -------------------------------
# Universal Functions
# -------------------------------

Universal functions (ufuncs) in NumPy are optimized functions that operate element-wise on arrays, supporting broadcasting, type casting, and vectorization for high performance.

In [3]:

arr = np.array([1, 4, 9, 16, 25])
sqrt_arr = np.sqrt(arr)    # Square root
sqrt_arr

array([1., 2., 3., 4., 5.])

In [4]:
exp_arr = np.exp(arr)      # Exponential
exp_arr

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06,
       7.20048993e+10])

In [5]:
log_arr = np.log(arr)      # Natural log
log_arr

array([0.        , 1.38629436, 2.19722458, 2.77258872, 3.21887582])

In [6]:
abs_arr = np.abs([-5, -10, 15])  # Absolute values
abs_arr

array([ 5, 10, 15])

# -------------------------------
# Aggregate Functions
# -------------------------------

Aggregate functions in NumPy perform a computation that reduces an array to a single value or smaller shape, such as sum(), mean(), min(), and max(), often applied along a specified axis.

In [11]:

agg_arr = np.array([[1, 2, 3], [4, 5, 6]])
total_sum = np.sum(agg_arr)
total_sum

np.int64(21)

In [12]:
minimum = np.min(agg_arr)
maximum = np.max(agg_arr)
minimum, maximum

(np.int64(1), np.int64(6))

In [13]:
mean_val = np.mean(agg_arr)
std_dev = np.std(agg_arr)
variance = np.var(agg_arr)
mean_val, std_dev, variance

(np.float64(3.5),
 np.float64(1.707825127659933),
 np.float64(2.9166666666666665))

In [17]:
max_index = np.argmax([10,2,3])  # Index of max value in flattened array
min_index = np.argmin([100,200,2])  # Index of min value in flattened array

max_index, min_index

(np.int64(0), np.int64(2))