###### Linear Algebra Functions

###### Random Module Functions

###### Stacking & Splitting Arrays

# 1 Linear Algebra Functions

Explanation:

np.linalg.inv(A): Computes the inverse of matrix A.

np.linalg.det(A): Calculates the determinant of A.

np.linalg.eig(A): Returns the eigenvalues and right eigenvectors of A.

np.linalg.norm(A): Computes the Frobenius norm of A.

np.trace(A): Calculates the sum of the diagonal elements of A.

np.linalg.solve(A, b): Solves the linear system Ax = b for x.

In [65]:
import numpy as np

# Define a 2x2 matrix
A = np.array([[4, 7],
              [2, 6]])

# Inverse of A
A_inv = np.linalg.inv(A)
print("Inverse of A:\n", A_inv)

Inverse of A:
 [[ 0.6 -0.7]
 [-0.2  0.4]]


In [56]:
# Determinant of A
A_det = np.linalg.det(A)
print(A)
print("Determinant of A:", A_det)

[[4 7]
 [2 6]]
Determinant of A: 10.000000000000002


In [57]:
# Eigenvalues and eigenvectors of A
eigenvalues, eigenvectors = np.linalg.eig(A)

print(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

[[4 7]
 [2 6]]
Eigenvalues: [1.12701665 8.87298335]
Eigenvectors:
 [[-0.92511345 -0.82071729]
 [ 0.37969079 -0.57133452]]


In [58]:
# Norm of A (Frobenius norm)
A_norm = np.linalg.norm(A)
print(A)
print("Norm of A:", A_norm)

[[4 7]
 [2 6]]
Norm of A: 10.246950765959598


In [63]:
# Trace of A (sum of diagonal elements)
A = np.array([[1,2,3,4,20],[10,20,30,40,20],[10,20,30,40,20],[10,20,30,40,20],[10,20,30,40,20]])
A_trace = np.trace(A)
print(A)
print("Trace of A:", A_trace)

[[ 1  2  3  4 20]
 [10 20 30 40 20]
 [10 20 30 40 20]
 [10 20 30 40 20]
 [10 20 30 40 20]]
Trace of A: 111


In [66]:
# Solve linear system Ax = b
b = np.array([1, 0])

print(A)
print(b)
x = np.linalg.solve(A, b)
print("Solution x:", x)

[[4 7]
 [2 6]]
[1 0]
Solution x: [ 0.6 -0.2]


# 2 Random Module Functions

Explanation:

np.random.seed(42): Sets the seed for random number generation to ensure reproducibility.

np.random.rand(3, 2): Generates a 3x2 array of random floats in the half-open interval [0.0, 1.0).

np.random.randn(3, 2): Generates a 3x2 array of samples from the standard normal distribution.

np.random.randint(0, 10, size=(3, 2)): Generates a 3x2 array of random integers between 0 and 9.

np.random.choice(...): Randomly selects elements from the given list.

np.random.shuffle(arr): Shuffles the array arr in-place.


In [40]:
import numpy as np

# Set seed for reproducibility
np.random.seed(42)

# Random floats in [0.0, 1.0)
rand_array = np.random.rand(4, 3)
print("Random array:\n", rand_array)

Random array:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]]


In [41]:
# Random samples from standard normal distribution
randn_array = np.random.randn(3, 2)
print("Random normal array:\n", randn_array)

Random normal array:
 [[-0.46947439  0.54256004]
 [-0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024]]


In [44]:
# Random integers between 0 (inclusive) and 10 (exclusive)
randint_array = np.random.randint(0, 20, size=(4,3))
print("Random integers:\n", randint_array)


Random integers:
 [[14  6 11]
 [ 7 14  2]
 [13 16  3]
 [17  7  3]]


In [47]:
# Random choice from a list
choices = np.random.choice(['apple', 'banana', 'cherry'], size=3)
print("Random choices:", choices)

Random choices: ['banana' 'cherry' 'cherry']


In [49]:
# Shuffle an array in-place
arr = np.arange(10)

np.random.shuffle(arr)
print("Shuffled array:", arr)

Shuffled array: [2 1 8 9 4 5 0 3 6 7]


# 3 Stacking & Splitting Arrays
Explanation:

np.vstack((a, b)): Stacks arrays vertically (row-wise).

np.hstack((a, b)): Stacks arrays horizontally (column-wise).

np.concatenate((a, b), axis=0): Concatenates arrays along the first axis (rows).

np.concatenate((a, b), axis=1): Concatenates arrays along the second axis (columns).

np.split(a, 2, axis=0): Splits array a into 2 equal parts along rows.

In [52]:
import numpy as np

# Define two arrays
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

print(a)
print(b, "\n")


# Vertical stacking
v_stack = np.vstack((a, b))
print("Vertical Stack:\n", v_stack)


# Horizontal stacking
h_stack = np.hstack((a, b))
print("Horizontal Stack:\n", h_stack)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]] 

Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]


In [53]:
# Concatenate along the first axis (rows)
concat_axis0 = np.concatenate((a, b), axis=0)
print("Concatenate along axis 0:\n", concat_axis0)

# Concatenate along the second axis (columns)
concat_axis1 = np.concatenate((a, b), axis=1)
print("Concatenate along axis 1:\n", concat_axis1)

Concatenate along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenate along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


In [54]:
# Split array into two equal parts along rows
a = np.array([[1,2,3],[3,5,6]])

np.split(a,2,axis=0)

[array([[1, 2, 3]]), array([[3, 5, 6]])]